### ISSUE TITLE
Invalid import

### ISSUE THREAD

**Issue by Strencher** [DevEvil99/Neptune-Discord-Theme#1]
See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)'s docs for CSS imports. 
https://github.com/DevEvil99/Neptune-Discord-Theme/blob/f21d4d4c2b012ebe43cbe523ac8dadd768fb92ca/Neptune.theme.css#L13

**Comment by DevEvil99** [comment]
fixed
